name: Deploy Next.js Project

on:
  push:
    branches:
      - main  # Trigger action only on pushes to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger action for pull requests to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # You can change the Node.js version according to your project requirements

    - name: Install dependencies
      run: npm install  # Use 'yarn install' if you are using Yarn

    - name: Build Next.js project
      run: npm run build  # Use 'yarn build' if you're using Yarn

    - name: Run Next.js tests
      run: npm run test  # Use 'yarn test' if you're using Yarn

    - name: Deploy Next.js project (optional)
      run: |
        npm run export  # Exports the Next.js app as static files
        # You can add your deployment steps here, for example, deploying to Vercel, Netlify, or AWS S3
        # Example for deploying to Vercel:
        # curl -X POST -F "file=@./out" https://vercel.com/api/deploy
      env:
        NEXT_PUBLIC_VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

    - name: Upload deployment artifacts (optional)
      uses: actions/upload-artifact@v2
      with:
        name: nextjs-artifacts
        path: ./out  # This path can vary based on your build output
